FROM dyne/devuan:beowulf
ENV debian buster

LABEL maintainer="Puria Nafisi Azizi <puria@dyne.org>" \
	  homepage="https://github.com/decodeproject/petition-tp-python"

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN apt-get update -y -q \
    && apt-get install -y -q \
    pkg-config \
    python3 \
    python3-pip \
    python3-stdeb \
    python3-dev \
    python3-protobuf \
    python3-cbor \
    python3-colorlog \
    python3-toml \
    python3-yaml \
    python3-zmq \
    zsh \
    && apt-get clean

RUN pip3 install grpcio-tools wheel

RUN mkdir -p /var/log/sawtooth /project

WORKDIR /project

# TODO: make sawtooth's release version an ENV var
# for latest git
# RUN git clone https://github.com/hyperledger/sawtooth-sdk-python.git /project/sawtooth-sdk-python
RUN wget https://github.com/hyperledger/sawtooth-sdk-python/archive/v1.2.2.tar.gz \
	&& tar xf v1.2.2.tar.gz && ln -s sawtooth-sdk-python-1.2.2 sawtooth-sdk-python \
    && /project/sawtooth-sdk-python/bin/protogen \
	&& pip3 install -e /project/sawtooth-sdk-python \
	&& rm -rf v1.2.2.tar.gz sawtooth-sdk-python-1.2.2 sawtooth-sdk-python

# using latest zenroom-tp-python on git
RUN git clone https://github.com/DECODEproject/petition-tp-python /project/petition-tp-python
RUN pip3 install -e /project/petition-tp-python/src

# install zenroom's cli binary and repo for tests
RUN wget https://sdk.dyne.org:4443/view/zenroom/job/zenroom-static-amd64/lastSuccessfulBuild/artifact/src/zenroom -O /usr/local/bin/zenroom && chmod +x /usr/local/bin/zenroom \
	&& git clone https://github.com/decodeproject/zenroom

# .zen is code
# .json is data
# here alice and bob are two rounds of the coconut flow fully generated
RUN cd /project/zenroom/test/zencode_coconut \
	&& cp *.zen /project/ \
	&& ./run_coconut_example.sh zenroom && ./run_petition_example.sh zenroom \
	&& mkdir -p /project/alice/ && cp -v *.json /project/alice/ \
	&& ./run_coconut_example.sh zenroom && ./run_petition_example.sh zenroom \
	&& mkdir -p /project/bob/ && cp -v *.json /project/bob/
# sha256 sums are checked to mark the difference by the two
# rounds. Here the JSON encoder order of output is not deterministic
# and needs to be sorted by the caller
RUN cat alice/* | sha256sum - > alice.sha256 \
	&& cat bob/* | sha256sum - > bob.sha256

# petition transaction middleware
RUN pip3 install 'fastapi[all]' && pip3 install hypercorn

ENV PATH=$PATH:/project/petition-tp-python/bin
WORKDIR /project
COPY petition-test.sh petition-test.sh
COPY petition-api.sh petition-api.sh
CMD petition-tp-python
