#!/usr/bin/env zsh

D=/var/lib/tor/dam
[[ -r $D/dam-private.key ]] && {
	pushd $D
	echo
	echo "-----BEGIN TOR-DAM KEYS BLOCK-----"
	echo
	tar -cf - dam-private.key dam-private.seed hostname | bzip2 -9 | base64
	echo
	echo "-----END TOR-DAM KEYS BLOCK-----"
	echo
	popd
}

S=/etc/sawtooth/keys
[[ -r $S/validator.priv ]] && {
	pushd $S
	echo
	echo "-----BEGIN SAWTOOTH VALIDATOR KEYS BLOCK-----"
	echo
	tar -cf - validator.priv validator.pub | bzip2 -9 | base64
	echo
	echo "-----END SAWTOOTH VALIDATOR KEYS BLOCK-----"
	echo
	popd
}

[[ -r $S/client.priv ]] && {
	pushd $K
	echo
	echo "-----BEGIN SAWTOOTH CLIENT KEYS BLOCK-----"
	echo
	tar -cf - client.priv client.pub | bzip2 -9 | base64
	echo
	echo "-----END SAWTOOTH CLIENT KEYS BLOCK-----"
	echo
	popd
}
