#!/usr/bin/env zsh

D=/var/lib/tor
[[ -r $D/.dam/dam-private.key ]] || HOME=$D dam-client -gen

S=/etc/sawtooth/keys
[[ -r $S/validator.priv ]] || sawadm keygen

[[ -r $S/client.priv ]] || sawtooth keygen --key-dir $S client

sawroom-address

