#!/usr/bin/env zsh

R=/etc/sawtooth
PATH=$PATH:$HOME

[ ! -f $R/keys/validator.priv ] && sawadm keygen

mode=`cat /etc/SAWROOM_NETWORK`

# https://sawtooth.hyperledger.org/docs/core/nightly/1-2/sysadmin_guide/off_chain_settings.html#configure-the-validator
cat <<EOF > /etc/sawtooth/validator.toml
bind = [
  "network:tcp://127.0.0.1:8800",
  "component:tcp://127.0.0.1:4004",
  "consensus:tcp://127.0.0.1:5050"
]
peering = "static"
endpoint = "tcp://127.0.0.1:8800"
peers = $(sawroom-seeds $mode)
scheduler = 'serial'
network_public_key = 'wFMwoOt>yFqI/ek.G[tfMMILHWw#vXB[Sv}>l>i)'
network_private_key = 'r&oJ5aQDj4+V]p2:Lz70Eu0x#m%IwzBdP(}&hWM*'
minimum_peer_connectivity = 3
maximum_peer_connectivity = 10
EOF

torsocks sawtooth-validator $SAWTOOTH_VALIDATOR_ARGS

                   # --endpoint       tcp://127.0.0.1:8800 \
                   # --bind component:tcp://127.0.0.1:4004 \
                   # --bind   network:tcp://127.0.0.1:8800 \
                   # --bind consensus:tcp://127.0.0.1:5050

# --scheduler serial \
# 			--peering static \
#             --network-auth challenge \

