#!/usr/bin/env zsh

R=/etc/sawtooth
PATH=$PATH:$HOME

[ -r /etc/SAWROOM_ENDPOINT ] || {
	print "Error: no advertised endpoint specified (external IP)"
	print "Please use the sawroom/run script to start."
	print "Validator launch aborted."
	exit 1
}

[ ! -f $R/keys/validator.priv ] && sawadm keygen

mode=`cat /etc/SAWROOM_NETWORK`

# https://sawtooth.hyperledger.org/docs/core/nightly/1-2/sysadmin_guide/off_chain_settings.html#configure-the-validator
cat <<EOF > /etc/sawtooth/validator.toml
bind = [
  "network:tcp://127.0.0.1:8800",
  "component:tcp://127.0.0.1:4004",
  "consensus:tcp://127.0.0.1:5050"
]
peering = "static"
endpoint = "tcp://`cat /etc/SAWROOM_ENDPOINT`:8800"
speers = $(sawroom-seeds $mode)
scheduler = 'serial'
network_public_key = 'wFMwoOt>yFqI/ek.G[tfMMILHWw#vXB[Sv}>l>i)'
network_private_key = 'r&oJ5aQDj4+V]p2:Lz70Eu0x#m%IwzBdP(}&hWM*'
minimum_peer_connectivity = 3
maximum_peer_connectivity = 1000
EOF

if [[ "$mode" == "TOR" ]]; then
	torsocks sawtooth-validator $SAWTOOTH_VALIDATOR_ARGS
else
	sawtooth-validator $SAWTOOTH_VALIDATOR_ARGS
fi



                   # --endpoint       tcp://127.0.0.1:8800 \
                   # --bind component:tcp://127.0.0.1:4004 \
                   # --bind   network:tcp://127.0.0.1:8800 \
                   # --bind consensus:tcp://127.0.0.1:5050

# --scheduler serial \
# 			--peering static \
#             --network-auth challenge \

