#!/usr/bin/env zsh

K=/etc/sawtooth/keys
L=/var/lib/tor/.dam
local dam
local pksaw
dam=""
pksaw=""

# see also /var/lib/tor/.dam/hostname
if [[ -r $L/hostname ]]; then
	dam=`cat $L/hostname`
else
	echo "Tor-Dam keys not found"
fi

if [[ -r $K/validator.pub ]]; then
	pksaw=`cat $K/validator.pub`
else
	echo "Sawtooth keys not found"
fi

[[ "$dam" != "" ]] && echo "TOR:$dam"
[[ "$pksaw" != "" ]] &&	echo "SAW:$pksaw"
echo "IP4:${"$(hostname -I)"[(w)1]}"
