#!/usr/bin/env zsh

[[ "$1" == "" ]] || {
	print "UID: $1"
	sed -e "s/1000/$1/" -i /etc/passwd
}

if [[ "`cat /etc/SAWROOM_NETWORK`" == "TOR" ]]; then
	cat /var/lib/tor/dam/hostname > /etc/SAWROOM_ENDPOINT
else
	echo "$2" > /etc/SAWROOM_ENDPOINT
fi
print "Endpoint: `cat /etc/SAWROOM_ENDPOINT`"

/etc/init.d/supervisor start

