#!/usr/bin/env zsh

[[ "$1" == "" ]] || {
	print "Starting Sawroom as ID $1"
	sed -e "s/1000/$1/" -i /etc/passwd
}

[[ -r /var/lib/sawtooth/block-chain-id ]] || {
	genesis=`cat /etc/SAWROOM_GENESIS`
	print "First run, importing genesis from: $genesis"
	curl $genesis | genesis-import
}

/etc/init.d/supervisor start

