#!/usr/bin/env zsh

# Script to parse an authorative list of peers formatted for sawroom
# and tor-dam and fill a json array inside scriptsa and configurations
# by Jaromil (2019), Public Domain

# arguments: SAW or DIR

pfx=${1:-"SAW"}
url=`cat /etc/SAWROOM_TRACKERS`
port=8800 # configured in dam-client
seeds=(`curl -s $url | grep "^${pfx}" | cut -d: -f2`)

out="["
if [[ "$pfx" == "SAW" ]]; then
	for i in $seeds; do
		out="${out}\"${i}\","
	done
elif [[ "$pfx" == "TOR" ]]; then
	# remove own onion address
	seeds=("${(@)seeds:#`cat /var/lib/tor/.dam/hostname`}")
	for i in $seeds; do
		out="${out}\"tcp://${i}:${port}\","
	done
elif [[ "$pfx" == "IP4" ]]; then
	# remove own ipv4 address
	own=${"$(hostname -I)"[(w)1]}
	seeds=("${(@)seeds:#$own}")
	for i in $seeds; do
		out="${out}\"tcp://${i}:${port}\","
	done
fi
out[${#out}]="]"
print $out
