#!/usr/bin/env zsh

[[ "$1" == "" ]] || {
	print "Starting Sawroom as UID $1"
	sed -e "s/1000/$1/" -i /etc/passwd
}

[[ "$2" == "" ]] || {
	print "Advertised endpoint: $2"
	sed -e "s/OWNIP/$2/" -i /usr/local/bin/sawroom-validator
}

/etc/init.d/supervisor start

